apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: docker.io/jauneloke/node-next-app
      name: webapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 3080
