openapi: 3.0.0
info:
  title: Express API
  description: API Node JS + Express JS
  version: 0.1.0
servers:
  - url: "http://localhost:3000/"
    description: Development server
paths:
  /api/post:
    get:
      summary: Returns a list of post.
      description: Get all post
      responses:
        "200":
          description: A JSON array of post
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
