# Communication entre les applications
# Point d'entrée unique
apiVersion: v1
kind: Service
metadata:
  name: node-next-app-service
  labels:
    run: node-next-app
spec:
  ports:
    - port: 3080
      protocol: TCP
  selector:
    app: node-next-app
  type: NodePort
